<?php

namespace Acme\Bundle\QuizzBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuizzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
   public function getQuestionByQuizz($quizzId)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->add('select', 'q')
            ->add('from', 'AcmeQuizzBundle:Question q')
            ->add('where', 'q.quizz_id = :quizz_id')
            ->setParameter('quizz_id', $quizzId)
            ->getQuery()
            ->getResult();
    }
}
