<?php

namespace Acme\Bundle\QuizzBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuizzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizzRepository extends EntityRepository
{

public function getAllQuizz(){
$quizz = $this->getDoctrine()
        ->getRepository('AcmeQuizzBundle:Quizz')
        ->find($id)
        ->find($titre)
        ->find($categorie);
    }
}
